trigger:
  batch: true
  branches:
    include:
    - master
    - release/3.x
    - release/5.0

pr:
  branches:
    include:
    - master
    - release/3.x
    - release/5.0
    - templates

jobs:
- job: test
  strategy:
    parallel: 200

  pool:
    name: NetCorePublic-Pool
    queue: BuildPool.Ubuntu.1604.Amd64.Open
  steps:
  - script: |
    chmod +x ./curl-test.sh
    ./curl-test.sh
